<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AlunoSimaed extends Model
{
    protected $table = 'alunos_simaed';
    protected $fillable = [
        'alunos_encontrados',
        'cadastros_encontrados',
        'ra',
        'cadastro_id',
        'cd_inep',
        'cadastro_censo',
        'aluno_sem_cd_inep',
        'cd_inep_erro',
        'cd_inep_diferente_censo',
        'cd_inep_censo',
        'nu_cpf',
        'cpf_igual_censo',
        'matricula_duplicada',
        'cpf_diferente_censo',
        'cpf_censo',
        'aluno_sem_cpf',
        'nu_cpf_valido',
        'cpf_duplicado',
        'mesmo_cpf_aluno_responsavel',
        'nis',
        'nis_invalido',
        'aluno_sem_nis',
        'pis',
        'nome',
        'nascimento',
        'dt_nascimento',
        'sem_nascimento_censo',
        'nascimento_diferente_censo',
        'sem_nascimento_simaed',
        'nascimento_censo',
        'nascimento_simaed_erro',
        'nascimento_censo_erro',
        'sexo',
        'pai',
        'mae',
        'mae_censo',
        'aluno_nome_mae_errado',
        'aluno_sem_nome_mae',
        'municipio',
        'censo',
        'escola',
        'periodo',
        'nivel',
        'modalidade',
        'etapa',
        'etapa_sgp',
        'turma',
        'cor',
        'endereco',
        'numero',
        'bairro',
        'municipio_endereco',
        'uf',
        'cep',
        'transporte_escolar',
        'nome_social',
        'possui_deficiencia',
        'deficiencia',
        'origem_informacao_aee',
        'telefone',
        'celular',
        'email',
        'responsavel',
        'responsavel_tel',
        'responsavel_cpf',
        'aluno_id_responsavel_cpf',
        'responsavel_cpf_invalido',
        'responsavel_sem_cpf',
        'nu_identidade',
        'orgao_expedidor',
        'uf_identidade',
        'data_expedicao',
        'bolsa_familia',
        'cartao_sus',
        'turno',
        'data_matricula',
        'situacao_matricula',
        'situacao_mec',
        'data_encerramento',
        'ano_referencia',
        'naturalidade',
        'uf_naturalidade',
        'sem_naturalidade',
        'nacionalidade',
        'sem_nacionalidade',
        'obs',
        'created_at',
        'updated_at',
        'tipo_matricula'
    ];

    public $timestamps = false;

}
